# Generated by Django 4.2.5 on 2023-09-17 10:35

from django.db import migrations, models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_url', models.CharField(max_length=255, verbose_name='Ссылка на новость')),
                ('post_title', models.CharField(max_length=255, verbose_name='Заголовок новости')),
                ('date_create', unixtimestampfield.fields.UnixTimeStampField(verbose_name='Дата публикации')),
                ('post_text', models.TextField(max_length=255, verbose_name='Текст новости')),
                ('post_image', models.ImageField(upload_to='images', verbose_name='Изображение к новости')),
                ('post_id', models.PositiveSmallIntegerField(max_length=255, verbose_name='uid новости')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
