# Generated by Django 4.2.5 on 2023-09-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='post_id',
            field=models.PositiveSmallIntegerField(verbose_name='uid новости'),
        ),
    ]
