# Generated by Django 4.2.5 on 2023-09-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='post_id',
            field=models.CharField(max_length=255, verbose_name='uid новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Изображение к новости'),
        ),
    ]
