# Generated by Django 4.2.5 on 2023-09-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_post_id_alter_news_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='post_image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Изображение к новости'),
        ),
    ]
