# Generated by Django 4.2.5 on 2023-09-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date_create',
            field=models.CharField(max_length=255, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='news',
            name='post_text',
            field=models.TextField(verbose_name='Текст новости'),
        ),
    ]
